services:
  backend:
    build: ./backend
    env_file:
      - backend/.env
    container_name: backend_app
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    restart: unless-stopped
      
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend_app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    
volumes:
  mongodb_data: